#include "intellino.h"
void intellino_train (uint32_t* data_ptr, uint8_t cat) {
    asm volatile ( ".set noreorder");
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(  0));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(  4));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(  8));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 12));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 16));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 20));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 24));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 28));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 32));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 36));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 40));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 44));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 48));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 52));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 56));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 60));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 64));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 68));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 72));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 76));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 80));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 84));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 88));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 92));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"( 96));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(100));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(104));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(108));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(112));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(116));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(120));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(124));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(128));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(132));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(136));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(140));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(144));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(148));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(152));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(156));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(160));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(164));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(168));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(172));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(176));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(180));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(184));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(188));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(192));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(196));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(200));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(204));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(208));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(212));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(216));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(220));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(224));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(228));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(232));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(236));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(240));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(244));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(248));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(252));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(256));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(260));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(264));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(268));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(272));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(276));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(280));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(284));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(288));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(292));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(296));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(300));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(304));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(308));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(312));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(316));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(320));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(324));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(328));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(332));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(336));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(340));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(344));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(348));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(352));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(356));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(360));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(364));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(368));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(372));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(376));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(380));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(384));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(388));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(392));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(396));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(400));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(404));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(408));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(412));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(416));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(420));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(424));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(428));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(432));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(436));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(440));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(444));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(448));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(452));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(456));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(460));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(464));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(468));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(472));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(476));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(480));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(484));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(488));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(492));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(496));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(500));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(504));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(508));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(512));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(516));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(520));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(524));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(528));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(532));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(536));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(540));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(544));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(548));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(552));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(556));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(560));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(564));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(568));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(572));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(576));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(580));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(584));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(588));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(592));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(596));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(600));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(604));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(608));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(612));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(616));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(620));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(624));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(628));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(632));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(636));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(640));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(644));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(648));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(652));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(656));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(660));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(664));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(668));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(672));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(676));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(680));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(684));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(688));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(692));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(696));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(700));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(704));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(708));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(712));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(716));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(720));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(724));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(728));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(732));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(736));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(740));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(744));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(748));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(752));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(756));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(760));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(764));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(768));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(772));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(776));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(780));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(784));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(788));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(792));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(796));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(800));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(804));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(808));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(812));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(816));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(820));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(824));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(828));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(832));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(836));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(840));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(844));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(848));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(852));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(856));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(860));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(864));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(868));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(872));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(876));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(880));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(884));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(888));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(892));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(896));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(900));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(904));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(908));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(912));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(916));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(920));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(924));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(928));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(932));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(936));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(940));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(944));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(948));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(952));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(956));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(960));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(964));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(968));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(972));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(976));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(980));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(984));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(988));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(992));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(996));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(1000));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(1004));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(1008));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(1012));
    asm volatile ( "lwc2 comp,  %0($a0)"::"i"(1016));
    asm volatile ( "lwc2 lcomp, %0($a0)"::"i"(1020));
    asm volatile ( "mtc2 $a1, cat");
    asm volatile ( ".set reorder");
}
Intellino_Result intellino_inference (uint32_t* data_ptr) {
    Intellino_Result result;
    asm volatile ( "add  $at,   %0, $0" ::"r"(data_ptr));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(  0));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(  4));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(  8));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 12));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 16));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 20));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 24));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 28));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 32));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 36));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 40));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 44));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 48));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 52));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 56));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 60));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 64));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 68));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 72));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 76));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 80));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 84));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 88));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 92));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"( 96));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(100));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(104));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(108));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(112));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(116));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(120));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(124));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(128));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(132));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(136));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(140));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(144));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(148));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(152));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(156));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(160));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(164));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(168));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(172));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(176));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(180));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(184));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(188));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(192));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(196));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(200));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(204));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(208));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(212));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(216));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(220));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(224));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(228));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(232));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(236));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(240));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(244));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(248));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(252));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(256));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(260));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(264));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(268));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(272));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(276));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(280));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(284));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(288));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(292));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(296));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(300));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(304));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(308));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(312));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(316));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(320));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(324));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(328));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(332));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(336));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(340));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(344));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(348));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(352));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(356));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(360));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(364));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(368));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(372));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(376));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(380));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(384));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(388));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(392));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(396));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(400));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(404));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(408));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(412));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(416));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(420));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(424));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(428));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(432));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(436));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(440));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(444));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(448));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(452));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(456));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(460));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(464));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(468));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(472));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(476));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(480));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(484));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(488));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(492));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(496));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(500));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(504));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(508));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(512));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(516));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(520));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(524));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(528));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(532));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(536));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(540));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(544));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(548));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(552));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(556));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(560));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(564));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(568));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(572));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(576));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(580));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(584));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(588));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(592));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(596));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(600));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(604));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(608));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(612));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(616));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(620));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(624));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(628));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(632));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(636));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(640));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(644));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(648));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(652));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(656));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(660));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(664));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(668));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(672));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(676));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(680));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(684));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(688));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(692));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(696));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(700));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(704));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(708));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(712));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(716));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(720));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(724));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(728));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(732));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(736));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(740));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(744));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(748));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(752));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(756));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(760));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(764));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(768));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(772));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(776));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(780));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(784));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(788));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(792));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(796));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(800));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(804));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(808));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(812));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(816));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(820));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(824));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(828));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(832));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(836));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(840));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(844));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(848));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(852));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(856));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(860));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(864));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(868));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(872));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(876));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(880));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(884));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(888));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(892));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(896));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(900));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(904));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(908));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(912));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(916));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(920));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(924));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(928));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(932));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(936));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(940));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(944));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(948));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(952));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(956));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(960));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(964));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(968));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(972));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(976));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(980));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(984));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(988));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(992));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(996));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(1000));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(1004));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(1008));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(1012));
    asm volatile ( "lwc2 comp,  %0($at)"::"i"(1016));
    asm volatile ( "lwc2 lcomp, %0($at)"::"i"(1020));
    asm volatile ( "nop\n\t \
                    nop\n\t \
                    nop\n\t \
                    nop\n\t \
                    nop");
    asm volatile ( "mfc2 %0, cat\n\t \
                    mfc2 %1, dist"
                   : "=r" (result.Category),
                     "=r" (result.Distance)
                   : );
    return result;
}

void intellino_forget (uint8_t nid) {
    asm volatile ( "mtc2 %0, nid"::"r"(nid));
    asm volatile ( "mtc2 %0, forget"::"r"(nid));
}

void intellino_clear () {
    asm volatile ( "mtc2 $0, clear");
}
